### ISSUE TITLE
Reduce amount of data sent

### ISSUE THREAD

**Issue by saurabhmathur96** [IEEECS-VIT/riviera-api#25]
Limit the fields sent in /events/all to id, name, category and chapter

Allow public access to get /events/id and send rest of public data there

**Comment by saurabhmathur96** [comment]
Update the table in readme too

**Comment by saurabhmathur96** [comment]
Deferred till final data is received

**Comment by Vishwajeetsinh98** [comment]
Mapped only the selected events, data should be considerably reduced by now.
