### ISSUE TITLE
Request validation

### ISSUE THREAD

**Issue by saurabhmathur96** [IEEECS-VIT/riviera-api#30]
Check the request body for presence of all parameters before processing it (make a middleware, maybe?)

```
req.post('/', checkFields(['field1', ...,]), function (req, res, next) { .. })
```

Send 400 bad request if a field is missing

https://github.com/nettofarah/property-validator

**Comment by saurabhmathur96** [comment]
Note that JS silently ignores if an undefined property is used. This issue it to avoid data loss in such a case

**Comment by Vishwajeetsinh98** [comment]
Please check out the changes. If found okay, will push to heroku

**Comment by saurabhmathur96** [comment]
.validateBody method is used instead of .checkPresence here
https://github.com/IEEECS-VIT/riviera-api/blob/2cdd170210bba5ca3681b8fcf82dcd8ac543d4e7/routes/v1/index.js#L12

Is there any specific reason for the same ?

**Comment by saurabhmathur96** [comment]
I meant .presence not .checkPresence

**Comment by saurabhmathur96** [comment]
Make a generic closure based property validation middleware like checkUserType instead of defining checks separately

https://github.com/IEEECS-VIT/riviera-api/blob/master/utils/util.js

**Comment by Vishwajeetsinh98** [comment]
Done. Requests are getting validated successfully.
