### ISSUE TITLE
Messages Reponse 'by' and 'to' data

### ISSUE THREAD

**Issue by karishnu** [IEEECS-VIT/riviera-api#31]
Return 'by' and 'to' data in messages reponse (as sent during requests)

**Comment by saurabhmathur96** [comment]
Each coordinator can only get his/her messages, so "to" seems redundant

**Comment by karishnu** [comment]
Just 'by' then

**Comment by Vishwajeetsinh98** [comment]
'by' is the admins. I don't see the need of revealing the identity of the admins.
